Repository conrad-blucher-institute/semaphore, pull requests merged in 2023-11, with the labels that each got.

#106 96 add filtering by interval to selection method
  src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
  src/tests/test_SQLAlchemyORM.py
Labels: enhancement, Refactor

#111 109 refactor dataingestion classes to use new db schema and object schema
  src/DataIngestion/DataIngestion/NOAATANDC.py
  src/DataIngestion/IDataIngestion.py
  src/tests/test_NOAATANDC.py
Labels: Refactor

#108 107 refactor seriesprovider to reflect new schema
  docs/dbml.png
  src/SeriesProvider/SeriesProvider.py
  src/tests/test_SeriesProvider.py
Labels: Refactor

#115 Fixing index out of range bug in select output if row requested isn't…
  src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
Labels: bug

#113 Move parse_date to utility.py. (Silly me.)
  src/API/apiDriver.py
  src/API/datetime_handler.py
Labels: Refactor

#117 Updating test
  src/tests/test_DataClasses.py
Labels: bug, Refactor

#119 fixing final bugs
  data/dspec/test_dspec.json
  src/ModelExecution/IOutputHandler.py
  src/ModelExecution/OutputHandler/OnePackedFloat.py
  src/ModelExecution/inputGatherer.py
  src/ModelExecution/modelWrapper.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
  src/tests/test_DataClasses.py
  src/tests/test_InputGatherer.py
  src/tests/test_SeriesProvider.py
Labels: bug

#124 120 the api test cant work because to get that data from data ingestion you have to supply an interval
  src/DataIngestion/DataIngestion/NOAATANDC.py
  src/tests/test_API.py
  src/tests/test_NOAATANDC.py
Labels: bug, Refactor

#126 Readded datum for AK for inputs table, but datum is now required
  src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
Labels: bug, Refactor

#123 79 create tcoon lighthouse ingestion class
  data/dspec/MLP-OP.json
  src/DataIngestion/DataIngestion/LIGHTHOUSE.py
  src/tests/test_LIGHTHOUSE.py
Labels: enhancement

#130 Making interval optional for inputs
  src/ModelExecution/inputGatherer.py
Labels: bug

#133 132 nothing being inserted into input table
  src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
Labels: bug

#121 66 create ndfd ingestion class
  requirements.txt
  src/DataIngestion/DataIngestion/NDFD.py
  src/tests/test_NDFD.py
Labels: enhancement

#139 Better error handling
  src/ModelExecution/modelWrapper.py
Labels: enhancement
