Repository conrad-blucher-institute/semaphore, pull requests merged in 2023-09, with the labels that each got.

#54 Added steps for creating virtual environment to README.md
  README.md
Labels: enhancement

#62 Fixing 00 "bug"
  data/dspec/test_dspec.json
  src/ModelExecution/inputGatherer.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/SeriesStorage/SS_SQLLite.py
Labels: bug

#65 Not forcing outputs to have a datums
  src/ModelExecution/inputGatherer.py
Labels: bug

#68 adding dataClassification parameter and methods
  data/dspec/test_dspec.json
  src/DataClasses.py
  src/ModelExecution/dspec.py
  src/ModelExecution/inputGatherer.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/ISeriesStorage.py
  src/SeriesStorage/SeriesStorage/SS_SQLLite.py
Labels: Refactor

#70 67 finish refactoring outputs
  data/dspec/test_dspec.json
  src/DataClasses.py
  src/ModelExecution/dspec.py
  src/ModelExecution/inputGatherer.py
  src/ModelExecution/modelWrapper.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/ISeriesStorage.py
  src/SeriesStorage/SeriesStorage/SS_SQLLite.py
Labels: Refactor

#71 63 dynamic imports and refactor mapping methods to factories
  data/dspec/test_dspec.json
  env.dict
  requirements.txt
  src/DataIngestion/DataIngestion/NOAATANDC.py
  src/DataIngestion/IDataIngestion.py
  src/ModelExecution/IOutputHandler.py
  src/ModelExecution/OutputHandler/OnePackedFloat.py
  src/ModelExecution/modelWrapper.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/ISeriesStorage.py
  src/SeriesStorage/SeriesStorage/SQLLite.py
  src/SeriesStorage/SeriesStorage/SS_Map.py
Labels: Refactor

#76 adding dbml
  docs/dbml.png
  docs/semaphore.dbml
Labels: documentation

#72 60 research api tech and develop plan to implamnet
  README.md
  requirements.txt
  src/API/__init__.py
  src/API/apiDriver.py
  src/API/datetime_handler.py
Labels: enhancement

#78 69 bug with lead time and time generated calculation
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/SeriesStorage/SQLLite.py
Labels: bug

#87 Removing the check completely
  src/SeriesStorage/SeriesStorage/SQLLite.py
Labels: bug
