Repository conrad-blucher-institute/semaphore, pull requests merged in 2024-09, with the labels that each got.

#427 Series provider refector w/ tests
  src/DataIngestion/DI_Classes/TEST_DI.py
  src/SeriesProvider/SeriesProvider.py
  src/SeriesStorage/SS_Classes/TEST_SS.py
  src/tests/IntegrationTests/test_SeriesProvider.py
  src/tests/UnitTests/test_unit_SeriesProvider.py
Labels: bug, Refactor

#429 Logging NDBC Error
  src/DataIngestion/DI_Classes/NDBC.py
Labels: documentation

#474 Notification refactor
  .env.dist
  docker-compose.yml
  requirements.txt
  src/ModelExecution/inputGatherer.py
  src/ModelExecution/modelWrapper.py
  src/SeriesProvider/SeriesProvider.py
  src/discord.py
  src/exceptions.py
  src/semaphoreRunner.py
Labels: enhancement
